### ISSUE TITLE
Broadlink RM4 Pro not able to be integrated in 0.108.6 vs

### ISSUE THREAD

**Issue by CarpeDiemRo** [mjg59/python-broadlink#343]
@felipediel @Danielhiversen 
I have 2 Broadlink RM Pro. One RM2 PRO and an RM4 Pro. RM2 works perfectly just from the first moment when I used it. After I upgraded HA to the latest version 0.108.6, I am not able to integrate RM4 Pro.
These are my settings from configuration.yaml

for the **switch**
```
  - platform: broadlink
    host: 192.168.1.166
    mac: 24:DF:A7:B9:C6:81
    type: rm4_pro
```
for the **sensor**
```
  - platform: broadlink
    host: 192.168.1.166
    mac: 24:DF:A7:B9:C6:81
    type: rm4_pro
    monitored_conditions:
      - 'temperature'
      - 'humidity'
```
Each time when I press Check Config button I receive the following message:

> Blockquote
Invalid config for [sensor.broadlink]: [type] is an invalid option for [sensor.broadlink]. Check: sensor.broadlink->type. (See ?, line ?). 
Invalid config for [switch.broadlink]: value is not allowed for dictionary value @ data['type']. Got 'rm4_pro'. (See ?, line ?). 

Can you help me please with some advises?

I want to mention that RM4 PRO is already Registered in the Broadlink app and has a fix IP.

[Later Edit]
I comment out type line from both blocks of code and I didn't receive any error when I check the configuration. After reboot, the switch is not available and the sensors return the following state
![Screenshot 2020-04-18 at 11 24 09](https://user-images.githubusercontent.com/38489167/79635188-267ce780-8178-11ea-9c52-40ab34fa2af4.png)
