### ISSUE TITLE
Broadlink RM4 PRO is not able to learn or to send IR Signal

### ISSUE THREAD

**Issue by CarpeDiemRo** [mjg59/python-broadlink#355]
@felipediel 

**Prerequisites**
1. Hassio updated to 109
2. RM4 Pro has been initialized and has a static IP
3. configuration.yaml
```
switch:
  - platform: broadlink
    host: 192.168.1.166
    mac: '24:DF:A7:B9:C6:81'
    type: rm4_pro
    timeout: 15
    switches:
      bedroom_tv:
        command_on: 'JgAcAB0dHB44HhweGx4cHR06HB0cHhwdHB8bHhwADQUAAAAAAAAAAAAAAAA='
        command_off: 'JgAaABweOR4bHhwdHB4dHRw6HhsdHR0dOTocAA0FAAAAAAAAAAAAAAAAAAA='
```

**Description of the issue**
1. From States tab I'm trying to switch on and of the entity switch.bedroom_tv
_Actual results_
a No led is blinking on RM4 Pro
b. No signal is send
2. From Service tab I'm trying to send broadlink.send command and press the power button of the Remote control
_Actual results_
a. The TV is power on
b. _No signal is received_ persistent notification is displayed
![Screenshot 2020-04-29 at 21 35 42](https://user-images.githubusercontent.com/38489167/80634167-b23d2080-8a62-11ea-8f38-5439184d59ef.png)

**Comment by felipediel** [comment]
@CarpeDiemRo Did you [disable the cloud](https://github.com/home-assistant/core/issues/30215#issuecomment-581159499)?

**Comment by CarpeDiemRo** [comment]
> @CarpeDiemRo Did you [disable the cloud](https://github.com/home-assistant/core/issues/30215#issuecomment-581159499)?

Do you mean Nabu Casa? I don't use it.

**Comment by felipediel** [comment]
No, Broadlink cloud. Follow the [instructions](https://github.com/home-assistant/core/issues/30215#issuecomment-581159499) to disable it.

**Comment by CarpeDiemRo** [comment]
I can confirm that everything it's working and I will describe the steps:

1. I delete the RM4 Pro from new Broadlink application
2. I reset the RM4 Pro by pressing the reset button 10 seconds
3.  I initialized RM4 Pro by using e-Control application. I tried with new Broadlink app but the integration with HA was unsuccessfully 
4. I put the required code into configuration.yaml defining as switch and sensor like this
```
switch:
  - platform: broadlink
    friendly_name: RM4 PRO
    host: 192.168.1.166
    mac: '24:DF:A7:B9:C6:81'
    type: rm4_pro
    timeout: 15
```
```
sensor:
  - platform: broadlink
    name: Bedroom
    host: 192.168.1.166
    mac: '24:DF:A7:B9:C6:81'
    type: rm4_pro
    monitored_conditions:
      - 'temperature'
      - 'humidity' 
```
5. I restarted the HA
6. I checked broadlink.learn
7. A valid persistent notification was returned

I will close this issue because everything works as design. Congrats @felipediel!
