### ISSUE TITLE
Home Assistant 2021.9.6 | Switches | Entities unavailable

### ISSUE THREAD

**Issue by bigsister-git** [mjg59/python-broadlink#617]
**Prerequisites**
The Remote is integrated and is displayed accordingly 
![Screenshot 2021-09-26 at 21 39 34](https://user-images.githubusercontent.com/84436465/134820047-654a77e3-e275-4807-b8cb-e279c6234e47.png)

In switch.yaml the switches are defined as follows

```
  - platform: broadlink
    mac: 81:C6:B9:A7:DF:25
    switches:
      - name: Philips ON/OFF
        command_on: JgBUAFcaDh4ODw4PLCsODw8ODw4ODw8ODw4PDg8ODw8ODw4PHQ4OHg4PDQAKqFcbDh4ODw4PKi0ODw0QDg8ODw4PDw4PDg4PDw4ODw4PHQ8OHQ4PDgANBQAA
      - name: Philips Volume UP/DOWN
        command_on: JgBUAFYbDx0NEA0QLCoQDhEMDRANEA8ODhAMEA4QDRANEBsfDg8NEA4PDQAKpVcbDR8ODw4PKywNEA4PDg8NEA8ODw4RDA4PDw4PDhweDRAOEA4PDgANBQAA
        command_off: JgBUAFgZDR8NEA8ODR4dDw4OEQ0ODw8ODg8NEA4PDRAODw4PHB4NEA4QHAAKs1UdDxwODw4PDh4eDgwRDBENEA8ODg8NEA4PEgsPDg8OHR0QDQ8OHgANBQAA 
```
and so on...

**Actual results**
1. The Switches are displayed as unavailable
![Screenshot 2021-09-26 at 21 42 47](https://user-images.githubusercontent.com/84436465/134820208-d5a0d9d6-96fb-48c2-b8ba-0e4388cd06a5.png)
2. In Developer Tools the swithes are not created
![Screenshot 2021-09-26 at 21 44 02](https://user-images.githubusercontent.com/84436465/134820241-72a5bff6-68a0-474c-8884-07ebed87aac9.png)

**What I did**
1.  Delete the remote -> Restart -> Initialised
2. Even though I took the MAC address from the router itself I reverse the order of the bites

**Expected results**
The switches must work as designed

**OBS**
I have Broadlnk outlet, too. These are working perfectly. The only issues that I have are with switches that are defined based on IR / RF codes.
